# https://taskfile.dev
version: "3"
tasks:
  install: forge install
  build: forge build
  dep-zkfair-test: deploy/deploy.sh zkfair-testnet
  # cat deployments/zkfair-testnet.json
  dep-x1-test: deploy/deploy.sh x1-testnet
  setup:
    deps:
      - install
      - build
